version: "3.8"

services:
  client:
    build:
      context: ./client
      args:
        VITE_API_URL: https://carwashdp603.ddns.net:3000/api
    # ports:
    #   - "8080:80"
    #   - "8443:443"
    depends_on:
      - server
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "3000:3000"  # nginx hace proxy a este puerto
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_AWS: ${DATABASE_URL_AWS}
      FRONTEND_URL: https://carwashdp603.ddns.net
      GMAIL_USER: estacionamientomartinez42@gmail.com
      GMAIL_PASS: "rdzd qkfa vxxg rfmj"

    volumes:
    - ./cert.pem:/app/cert.pem
    - ./key.pem:/app/key.pem
    networks:
      - app-network
    restart: unless-stopped


networks:
  app-network:
    driver: bridge
